#  异常处理

Rust中分为2类异常：

1. 可恢复的异常

   可恢复的异常通过 `Result<T, E>`来处理

2. 不可恢复的异常

​		对于不可恢复的异常，Rust通常会通过`panic!`宏来中断程序。



## panic!

让要程序抛出 `panic!`有2种方式：

1. 执行某些可以造成`panic!`的操作，比如访问数组时越界。
2. 显示的执行`panic!`宏





## 可恢复的异常

例如 `File::open`的返回值是 `Result<T, E>`，我们可以使用`match`表达式来处理这种情况，与 `Option<T>`类似



### 其他处理异常的方法：

- unwrap
  - 这是一个快速处理异常的方法，与`match`类似，如果结果是`Ok`，那么 `unwrap`则返回 `Ok`分支中的值。否则`unwrap`则会调用 `panic`宏。
- expect
  - 与 unwrap类似，只不过panic的的错误信息可以通过参数传入

## 错误传播

可以使用`?`来决定是否将异常返回至上层调用的函数。

```rust
use std::fs::File;
use std::io::{self, Read};

fn read_username_from_file() -> Result<String, io::Error> {
    let mut username_file = File::open("hello.txt")?;
    let mut username = String::new();
    username_file.read_to_string(&mut username)?;
    Ok(username)
}

```

对于第五行代码，如果文件成功打开，则代码继续向下执行。

否则，函数将提前结束并将错误信息返回到上层函数。



对于main函数，如果要使用`?`，则需要修改函数签名为: `Result<(), Box<dyn Error>>`